### ISSUE TITLE
SwiftUI views are @MainActor now

### ISSUE THREAD

**Issue by disbelief** [mattmassicotte/ConcurrencyRecipes#13]
Thanks for this fantastic resource, I learn so much better via these code examples.

Wanted to mention that SwiftUI Views are now marked `@MainActor @preconcurrency` in the latest version: https://developer.apple.com/documentation/swiftui/view

I think this means the SwiftUI recipe is now unnecessary, or at least only needed for older codebases?

**Comment by mattmassicotte** [comment]
Yes you are right! I've been neglecting this repo a little too much since the launch of the migration guide over here: https://www.swift.org/migration/documentation/migrationguide/.

But I should still at least pay a bit of attention...

**Comment by disbelief** [comment]
FWIF I had read the migration guide before finding this repo and still find it extremely valuable.

**Comment by mattmassicotte** [comment]
I'm glad to hear that! It definitely seems some more attention as, aside from this, a bunch of things have changed/improved in Swift 6.

Thank you for filing this. I really appreciate the nudge.
