### ISSUE TITLE
How to subscribe to a global actor's publisher?

### ISSUE THREAD

**Issue by mylaluna** [mattmassicotte/ConcurrencyRecipes#15]
I converted some of my singleton classes to global actors. Following is one example:

```swift

@globalActor actor MyActor: ObservableObject {
    
    static let shared = MyActor()
   
    @Published @MainActor var isBusy: Bool = false
    
     ...

}

```

In another class, I want to subscribe to the publisher of `isBusy` variable:

```swift
class MyClass: ObservableObject {

    private var cancellables = Set<AnyCancellable>()

    init() {
        Task {
            // Error: Type 'AnyCancellable' does not conform to the 'Sendable' protocol
            // Error: Class 'AnyCancellable' does not conform to the 'Sendable' protocol (Combine.AnyCancellable)
            await MyActor.shared.$isBusy
                .sink {
                    ...
                }
                .store(in: &cancellables)
        }
    }
   ...
}

```

However, I will get an error for doing this. 
I have been trying to create some workaround solutions but none of them work.

What is the recommended way to subscribe to a publisher from an actor or global actor?

**Comment by mattmassicotte** [comment]
will answer over here https://forums.swift.org/t/how-to-subscribe-to-an-actors-publisher/75742
